services:
  db:
    image: postgres:18.4
    container_name: allsafe_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_HOST_PORT}:${DB_PORT}'

  redis:
    container_name: allsafe_redis
    image: redis:8.8.1-alpine
    ports:
      - '${REDIS_HOST_PORT}:${REDIS_PORT}'
    volumes:
      - redis-data:/data

  app:
    container_name: allsafe_app
    build: .
    ports:
      - '${ALLSAFE_HOST_PORT}:${ALLSAFE_PORT}'
    depends_on:
      db:
        restart: true
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env

volumes:
  redis-data:
    name: 'redis'

  db-data:
    name: 'postgres'