"""change username length limit in User schema

Revision ID: 1a65d85a280e
Revises: f9d8754e3d37
Create Date: 2026-08-21 10:33:46.054867

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a65d85a280e"
down_revision: str | Sequence[str] | None = "f9d8754e3d37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
