"""change GamePlayer, Game models' fields

Revision ID: 368d53ac14e5
Revises: 0eef8edd2853
Create Date: 2026-08-26 20:41:28.664227

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "368d53ac14e5"
down_revision: str | Sequence[str] | None = "0eef8edd2853"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game_players",
        "status",
        existing_type=postgresql.ENUM("ACTIVE", "ELIMINATED", "LEFT", name="player_status"),
        server_default=sa.text("'ACTIVE'"),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "status",
        existing_type=postgresql.ENUM("WAITING", "IN_PROGRESS", "FINISHED", "CANCELLED", name="game_status"),
        server_default=sa.text("'WAITING'"),
        existing_nullable=False,
    )
    op.alter_column(
        "games",
        "max_players",
        existing_type=sa.SMALLINT(),
        server_default=sa.text("5"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "games", "max_players", existing_type=sa.SMALLINT(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "games",
        "status",
        existing_type=postgresql.ENUM("WAITING", "IN_PROGRESS", "FINISHED", "CANCELLED", name="game_status"),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "game_players",
        "status",
        existing_type=postgresql.ENUM("ACTIVE", "ELIMINATED", "LEFT", name="player_status"),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
