"""change User model's password_hash column character limits

Revision ID: 379aa4eb01b1
Revises: 69aa4e846f82
Create Date: 2026-08-22 13:54:15.783349

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "379aa4eb01b1"
down_revision: str | Sequence[str] | None = "69aa4e846f82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
