"""change User model's column name hash_password -> password_hash

Revision ID: 69aa4e846f82
Revises: 1a65d85a280e
Create Date: 2026-08-22 12:15:15.258747

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69aa4e846f82"
down_revision: str | Sequence[str] | None = "1a65d85a280e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password_hash", sa.String(length=50), nullable=False))
    op.drop_column("users", "hash_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hash_password", sa.VARCHAR(length=50), autoincrement=False, nullable=False)
    )
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
