"""add min_players_range, min_players_not_greater_than_max, game_owner_matches_access constraints; game_type, owner_id columns in game model

Revision ID: 6f9b0c930600
Revises: 368d53ac14e5
Create Date: 2026-08-29 12:49:08.400039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6f9b0c930600'
down_revision: Union[str, Sequence[str], None] = '368d53ac14e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

game_access_enum = postgresql.ENUM(
    "PUBLIC",
    "PRIVATE",
    name="game_access",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    game_access_enum.create(op.get_bind(), checkfirst=False)

    op.add_column('game_players', sa.Column('is_ready', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('games', sa.Column('game_type', sa.Enum('PUBLIC', 'PRIVATE', name='game_access'), server_default=sa.text("'PUBLIC'"), nullable=False))
    op.add_column('games', sa.Column('min_players', sa.SMALLINT(), server_default=sa.text('5'), nullable=False))
    op.add_column('games', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.alter_column('games', 'max_players',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('10'),
               existing_nullable=False)
    op.execute(
        """
        UPDATE games
        SET min_players = max_players
        WHERE min_players > max_players
        """
    )
    op.create_foreign_key(op.f('fk_games_owner_id_users'), 'games', 'users', ['owner_id'], ['id'])
    op.create_check_constraint(
        op.f("ck_games_min_players_range"),
        "games",
        "min_players BETWEEN 3 AND 20",
    )
    op.create_check_constraint(
        op.f("ck_games_min_players_not_greater_than_max"),
        "games",
        "min_players <= max_players",
    )
    op.create_check_constraint(
        op.f("ck_games_game_owner_matches_access"),
        "games",
        """
        (game_type = 'PUBLIC' AND owner_id IS NULL)
        OR
        (game_type = 'PRIVATE' AND owner_id IS NOT NULL)
        """,
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_games_game_owner_matches_access"),
        "games",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_games_min_players_not_greater_than_max"),
        "games",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_games_min_players_range"),
        "games",
        type_="check",
    )

    op.drop_constraint(
        op.f("fk_games_owner_id_users"),
        "games",
        type_="foreignkey",
    )

    op.alter_column(
        "games",
        "max_players",
        existing_type=sa.SMALLINT(),
        server_default=sa.text("5"),
        existing_nullable=False,
    )

    op.drop_column("games", "owner_id")
    op.drop_column("games", "min_players")
    op.drop_column("games", "game_type")
    op.drop_column("game_players", "is_ready")

    game_access_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
