"""add game chat schema

Revision ID: 8b0c6806130f
Revises: 1886c91f2a3f
Create Date: 2026-08-20 17:08:56.923612

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b0c6806130f"
down_revision: str | Sequence[str] | None = "1886c91f2a3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("WAITING", "IN_PROGRESS", "FINISHED", "CANCELLED", name="game_status"),
            nullable=False,
        ),
        sa.Column("max_players", sa.SMALLINT(), nullable=False),
        sa.Column("current_round_number", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("winner_player_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("max_players BETWEEN 3 AND 20", name=op.f("ck_games_max_players_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "game_players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "ELIMINATED", "LEFT", name="player_status"), nullable=False),
        sa.Column("eliminated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("joined_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name=op.f("fk_game_players_game_id_games")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_game_players_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_game_players")),
        sa.UniqueConstraint("game_id", "user_id", name="uq_game_players_game_user"),
    )
    op.create_foreign_key(
        op.f("fk_games_winner_player_id_game_players"),
        "games",
        "game_players",
        ["winner_player_id"],
        ["id"],
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("sender_player_id", sa.Uuid(), nullable=True),
        sa.Column("message_type", sa.Enum("USER", "SYSTEM", name="message_type"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "\n            (message_type = 'USER' AND sender_player_id IS NOT NULL)\n            OR\n            (message_type = 'SYSTEM' AND sender_player_id IS NULL)\n            ",
            name=op.f("ck_messages_type_sender"),
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name=op.f("fk_messages_game_id_games")),
        sa.ForeignKeyConstraint(
            ["sender_player_id"], ["game_players.id"], name=op.f("fk_messages_sender_player_id_game_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_table(
        "rounds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DISCUSSION", "VOTING", "TIEBREAK_VOTING", "RESULT", "FINISHED", name="round_status"),
            nullable=False,
        ),
        sa.Column("eliminated_player_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("voting_ends_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint("round_number > 0", name=op.f("ck_rounds_number_positive")),
        sa.ForeignKeyConstraint(
            ["eliminated_player_id"],
            ["game_players.id"],
            name=op.f("fk_rounds_eliminated_player_id_game_players"),
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name=op.f("fk_rounds_game_id_games")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rounds")),
        sa.UniqueConstraint("game_id", "round_number", name="uq_rounds_game_round"),
    )
    op.create_table(
        "votes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("round_id", sa.Uuid(), nullable=False),
        sa.Column("voter_player_id", sa.Uuid(), nullable=False),
        sa.Column("target_player_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("voter_player_id <> target_player_id", name=op.f("ck_votes_no_self_vote")),
        sa.ForeignKeyConstraint(["round_id"], ["rounds.id"], name=op.f("fk_votes_round_id_rounds")),
        sa.ForeignKeyConstraint(
            ["target_player_id"], ["game_players.id"], name=op.f("fk_votes_target_player_id_game_players")
        ),
        sa.ForeignKeyConstraint(
            ["voter_player_id"], ["game_players.id"], name=op.f("fk_votes_voter_player_id_game_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_votes")),
        sa.UniqueConstraint("round_id", "voter_player_id", name="uq_votes_round_voter"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_games_winner_player_id_game_players"),
        "games",
        type_="foreignkey",
    )

    op.drop_table("votes")
    op.drop_table("rounds")
    op.drop_table("messages")
    op.drop_table("game_players")
    op.drop_table("users")
    op.drop_table("games")

    bind = op.get_bind()

    sa.Enum(
        "DISCUSSION",
        "VOTING",
        "TIEBREAK_VOTING",
        "RESULT",
        "FINISHED",
        name="round_status",
    ).drop(bind, checkfirst=True)

    sa.Enum(
        "USER",
        "SYSTEM",
        name="message_type",
    ).drop(bind, checkfirst=True)

    sa.Enum(
        "ACTIVE",
        "ELIMINATED",
        "LEFT",
        name="player_status",
    ).drop(bind, checkfirst=True)

    sa.Enum(
        "WAITING",
        "IN_PROGRESS",
        "FINISHED",
        "CANCELLED",
        name="game_status",
    ).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
