"""add hash_password field in User schema

Revision ID: f9d8754e3d37
Revises: 8b0c6806130f
Create Date: 2026-08-21 10:14:10.492278

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9d8754e3d37"
down_revision: str | Sequence[str] | None = "8b0c6806130f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hash_password", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hash_password")
    # ### end Alembic commands ###
